name: ZilaBrand.com
repository: zilabrand/zilabrand.github.io
permalink: pretty
exclude:
  - GemFile
  - Gemfile.lock
  - README.md
keep_files:
  - _script.js
  - _script.js.map
  - _style.css
  - _style.css.map
