name: ZilaBrand.com
repository: zilabrand/zilabrand.github.io
exclude:
  - GemFile
  - Gemfile.lock
  - README.md
include:
  # Prefix with underscores to separate from content
  - _script.js
  - _style.css
